<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dds-mbpro-67" ignored="0" name="ACC" tests="4" failures="1" timestamp="08 Jul 2018 15:50:13 GMT" time="13.101" errors="0">
  <testcase name="overloadedAssetAttachment" time="8.099" classname="acc_timeOut.sampleAccTests"/>
  <testcase name="permittedAssetAttachment" time="0.649" classname="acc_timeOut.sampleAccTests"/>
  <testcase name="testClaimCreation" time="0.235" classname="acc_timeOut.sampleAccTests"/>
  <testcase name="timedOutAssetAttachment" time="4.046" classname="acc_timeOut.sampleAccTests">
    <failure type="java.lang.AssertionError" message="Failure message expected [810] but found [0]">
      <![CDATA[java.lang.AssertionError: Failure message expected [810] but found [0]
at acc_timeOut.sampleAccTests.timedOutAssetAttachment(sampleAccTests.java:52)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- timedOutAssetAttachment -->
</testsuite> <!-- ACC -->
